version: '3.5'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: articles
    ports:
      - 5432:5432